FORMAT: 1A
HOST: https://repository.agilesigner.com:8443/Agile27

# CertificateRepositoryAPI

API para banco de Firmas y generación de Certificados.

## Solicitud de Certificado [/genCertificate]
Permite generar un certificado digital para una persona, retornando posteriormente un Base64 del X509

### Generar Solicitud de Certificado [POST]

+ Attributes (object)
    + Include User
    + Include CAinfo
    + certificateType (string, required) - Certificate type
    + expirationYears (string, required) - Certificate's expiration in ISO 8601 format
    + purpose (string) - Certificate's purpose


+ Request (application/json; charset=UTF-8)

            {
                "commonName": "JOHN DOE",
                "dni": "11111111-1",
                "cargo": "NADA",
                "organismo": "NADA",
                "entidad" : "NADA",
                "email": "example@agile.cl",
                "name": "TESTX",
                "entityProfile": "test",
                "certificateProfile": "SAI",
                "certificateType": "3",
                "expirationYears": "2016-01-15 13:13:13+00:00",    
                "purpose": "Samples"
            }
    

+ Response 201 (application/json; charset=UTF-8)
    + Attributes (Certificate)
    

## Habilitación de Certificados [/confirmCertificate]
Los certificados una vez validados por el ministro de fé, deben ser confirmados ante el banco de certificados para habilitar el uso de los mismos

### Habilitar Certificado [POST]

+ Attributes (object)
    + dni (string, required) - Certificate holder's unique identifier
    + fp (string, required) - Certificate's Fingerprint
    + hash (string, optional) - XML confirmation Hash is optional in attestor certificate

+ Request (application/json; charset=UTF-8)

+ Response 200

        El certificado ha sido correctamente confirmado y está disponible para usarse

+ Response 404

        El certificado no existe o no corresponde al usuario



## Solicitud de OTP [/getOTPSecret]
Para poder firmar con sus certificados (de tipo OTP) los ususarios deben obtener su secreto de "one time password" para 

### Solicitar OTP [GET]    

+ Attributes (object)
    + dni (string, required) - User's unique identifier (xxx-x)
    + fp (string, required) - Certificate's Fingerprint
    + appId (string, required) - Application's unique identifier (claimant)

+ Request (application/json; charset=UTF-8)

+ Response 200
    + Attributes (object)
        + secret (string) - Certificate's OTP secret

# Data Structures

## Certificate (object)
+ x509: "Base64" (string) - Certificate's pem in Base64 format

## User (object)
+ commonName (string, required) - User's common name 
+ dni (string, required) - User's unique identifier (xxx-x)
+ cargo (string) - User's position
+ organismo (string) - User's organism
+ entidad (string) - User's organism unit
+ email (string, required) - User's email address    

## CAinfo (object)
+ name (string, required) - CA name
+ entityProfile (string, required) - Entity Profile
+ certificateProfile (string, required) - Certificate Profile