FORMAT: 1A
HOST: https://repository.agilesigner.com:8443/Agile27

# CertificateRepositoryAPI

API para banco de Firmas y generación de Certificados.

## Solicitud de Certificado [/genCertificate]
Permite generar un certificado digital para una persona, retornando posteriormente un Base64 del X509

### Generar Solicitud de Certificado [POST]

+ Attributes (object)
    + Include User
    + Include CAinfo
    + certificateType (string, required) - Certificate type
    + expirationYears (string, required) - Certificate's expiration time in years
    

+ Request (application/json; charset=UTF-8)

+ Response 201 (application/json; charset=UTF-8)
    + Attributes (Certificate)

# Data Structures

## Certificate (object)
+ x509: "Base64" (string) - Certificate's pem in Base64 format

## User (object)
+ commonName (string, required) - User's common name 
+ dni (string, required) - User's unique identifier
+ cargo (string) - User's position
+ organismo (string) - User's organism
+ email (string, required) - User's email address    

## CAinfo (object)
+ name (string, required) - CA name
+ entityProfile (string, required) - Entity Profile
+ certificateProfile (string, required) - Certificate Profile